# Generated by Django 5.1.3 on 2024-11-12 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
